# Generated by Django 3.1.4 on 2021-07-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fieldofrecord_patientrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofrecord',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/patient/pathology_and_others'),
        ),
        migrations.AlterField(
            model_name='fieldofrecord',
            name='hint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fieldofrecord',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
