# Generated by Django 3.1.4 on 2021-08-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210807_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='images/discussion/category_thumbnails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.discussioncategory'),
        ),
    ]
