# Generated by Django 3.1.4 on 2021-08-12 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210807_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussioncommentvote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='discussionpostvote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='discussionsubcommentvote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', unique=True),
        ),
    ]
