# Generated by Django 3.1.4 on 2021-08-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210812_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussioncommentvote',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.discussioncomment'),
        ),
        migrations.AlterField(
            model_name='discussionpostvote',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.discussionpost'),
        ),
        migrations.AlterField(
            model_name='discussionsubcommentvote',
            name='sub_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.discussionsubcomment'),
        ),
    ]
