# Generated by Django 3.1.4 on 2021-09-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=150)),
                ('transaction_id', models.CharField(max_length=150)),
                ('payment_number', models.IntegerField(null=True)),
                ('appointment_time', models.DateField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorProfile', to='core.userprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientProfile', to='core.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
