# Generated by Django 3.1.4 on 2021-10-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='draft', max_length=80),
        ),
    ]
