# Generated by Django 3.1.4 on 2021-10-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211001_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='Male', max_length=50),
        ),
    ]
