# Generated by Django 3.1.4 on 2021-10-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='appointment_fee',
            field=models.IntegerField(null=True),
        ),
    ]
