# Generated by Django 3.1.4 on 2021-10-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userprofile_appointment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='transaction_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
