# Generated by Django 3.1.4 on 2021-10-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20211015_0730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
