# Generated by Django 3.1.4 on 2021-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20211017_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
