# Generated by Django 3.1.4 on 2021-10-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211017_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patinet_payment_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
