# Generated by Django 3.1.4 on 2021-10-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_appointment_patinet_payment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patinet_payment_number',
            new_name='patient_payment_number',
        ),
    ]
