# Generated by Django 4.0.2 on 2022-04-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_discussioncommentvote_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussioncommentvote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='discussionpostvote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='discussionsubcommentvote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', unique=True),
        ),
    ]
