# Generated by Django 4.0.2 on 2022-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_discussioncommentvote_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='patient_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
